### PR TITLE
Reflection controllers

### PR DESCRIPTION
**Pull request by MTheSestrim**
Implemented reflection-based routing. All that is needed is to use the MapGet method with a specific controller. Currently only supports Get methods. Index and empty string (in case of errors) actions refer to the default "/" route. The rest are mapped according to the method name, same as in ASP.NET Core.

### CODE REVIEW

**Review by ivaylokenov — CHANGES_REQUESTED** [review]
Add controller discovery functionality - find all controllers by reflection. They should inherit from the base Controller class and their name should end with the "Controller" suffix. It should not happen automatically - add a "MapControllers" method.

**Comment by MTheSestrim** [comment]
Added an extension method that maps all controllers in entry assembly. Comments explain functionality in more details. Currently no support for mapping anything other than get methods, so I've mapped "/Cats/Create" separately.

**Comment by MTheSestrim** [comment]
Fixed merge errors as you instructed. I have commented your MapControllers method to do so. If I am able to, I will update the functionality of my code to take advantage of the method attributes so it isn't left unfinished.

**Comment by MTheSestrim** [comment]
Updated my MapControllers method. It's very much like your own method, except I used two foreach cycles just so there could be something different. Maybe it could help some colleagues with understanding the logic better, I don't know. I have a separate GetRoutePath method, though I think it is wholly unnecessary, especially since I implemented your own MapDefaultRoutes method. Nonetheless, I thought it appropriate to finish my own work here for the sake of learning.

**Comment by ivaylokenov** [comment]
Closing because the code is almost identical to mine. Thank you for your work!

**Pull request closed without merging**
